name: tests-mamba

on:
  pull_request:
  push:
    branches: master

jobs:
  build-mamba:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment.yml
        init-shell: >-
          bash
        cache-environment: true
        post-cleanup: 'all'
    - name: Run non-mpi tests
      run: pytest -k test_mamba
      shell: micromamba-shell {0}
    - name: Run mpi tests
      run: mpirun -n 2 pytest -k test_mamba --with-mpi
      shell: micromamba-shell {0}